/*
 This file is auto-generated by the statrep package.
 Do not edit this file or your changes will be lost.
 Edit the LaTeX file instead.
 
 See the statrep package documentation and the file
 statrep.cfg for information on these settings.
 */
 
 
%include "./8320_SR_preamble.sas" /nosource;
/* Remove all output files. */
%cleandir(., tex, tex);
%cleandir(., png, png);
%cleandir(., lst, lst);


/* Start program with a null title. */
title;

%write(anova,store=class,type=listing) 

%write(covest,store=class,type=listing) 

%write(h4re10,store=class,type=listing) 

%write(h4re23,store=class,type=listing) 

%output(class)
proc mixed data=alzheim method=ml noitprint;
class idno group;
model score=group*visit/ s outp=rdint;
random int/subject=idno;
run;

%endoutput(class)

%output(class)
proc mixed data=alzheim method=ml noitprint covtest;
class idno group;
model score=group*visit/ s outp=rdcoe;
random int visit/subject=idno type=un;
run;

%endoutput(class)

proc mixed data=alzheim noitprint covtest;
class group visit;
model score=group|visit/ s outp=repmar;
repeated visit / subject=idno type=ar(1);
run;

proc mixed data=alzheim noitprint covtest;
class group visit;
model score=group|visit/ s outp=repun;
repeated visit / subject=idno type=un;
run;

