/*
 This file is auto-generated by the statrep package.
 Do not edit this file or your changes will be lost.
 Edit the LaTeX file instead.
 
 See the statrep package documentation and the file
 statrep.cfg for information on these settings.
 */
 
 
%include "./8320_SR_preamble.sas" /nosource;
/* Remove all output files. */
%cleandir(., tex, tex);
%cleandir(., png, png);
%cleandir(., lst, lst);


/* Start program with a null title. */
title;

proc genmod data = da.h3q1;
model daysabs = male math langarts /dist=negbin;
run;
proc genmod data = da.h3q1;
model daysabs = / dist=negbin;
run;
quit;

%write(h3re5a,store=class,type=listing) 

%write(scatter,store=class,type=graphic) 

%output(class)
PROC LOGISTIC DATA=q31 DESCENDING;
class cylinders modelyear origin;
MODEL mpg01=cylinders displacement horsepower weight
 acceleration modelyear origin/selection=stepwise;
RUN;

%endoutput(class)

%write(h3re34,store=class,type=listing) 

%write(h3re38,store=class,type=listing) 

%write(h3re39,store=class,type=listing) 

%write(h3re31,store=class,type=listing) 

%output(class)
PROC LOGISTIC DATA=q31 DESCENDING outmodel=model;
class cylinders modelyear origin;
MODEL mpg01=cylinders weight modelyear/ scale=none AGGREGATE;
score data=q31 out=score fitstat;
RUN;
PROC LOGISTIC inmodel=model;
score data=q3t1 out=Scoret fitstat;
RUN;
proc freq data=scoret;
tables F_mpg01* I_mpg01/nocol nocum norow nopercent;
run;

%endoutput(class)

%write(h3re40,store=class,type=listing) 

%write(h3re41,store=class,type=listing) 

%write(h3re47,store=class,type=listing) 

%write(h3re9,store=class,type=graphic) 

%write(h3re66,store=class,type=listing) 

