/*
 This file is auto-generated by the statrep package.
 Do not edit this file or your changes will be lost.
 Edit the LaTeX file instead.
 
 See the statrep package documentation and the file
 statrep.cfg for information on these settings.
 */
 
 
%include "./code_SR_preamble.sas" /nosource;
/* Remove all output files. */
%cleandir(., tex, tex);
%cleandir(., png, png);
%cleandir(., lst, lst);


/* Start program with a null title. */
title;

%output(class)
libname da2 'C:\Users\psy6b\Desktop\8320 datasets';
ods graphics on;
options ls=65 ps=35;
title;

data da2.h7q1;
infile 'C:\Users\psy6b\Desktop\8320 datasets\decathlon.dat';
input run100 Ljump shot Hjump run400 hurdle discus polevlt javelin run1500 score;
race_100=-race_100;
race_400=-race_400;
hurdles=-hurdles;
run_1500=-run_1500;
run;
proc univariate data=da2.h7q1 plots;
var score;
run;
data da2.h7q1;
set da2.h7q1;
if score>6000;
run;
proc princomp data=da2.h7q1 out=q1out;
var run100--run1500;
run;
proc rank data=q1out out=q1out descending;
var score;
ranks posn;
run;
data labels;
set q1out;
retain xsys ysys '2';
y=prin1;
x=prin2;
text=put(posn,2.);
keep xsys ysys x y text;
run;
proc gplot data=q1out;
plot prin1*prin2 / annotate=labels; symbol v=none;
run;
goptions reset=symbol;
proc gplot data=q1out;
plot score*(prin1 prin2);
run;
proc corr data=q1out;
var score prin1 prin2;
run;






data da2.h7q2(type=corr);
infile 'C:\Users\psy6b\Desktop\8320 datasets\pain.dat' missover;
input _type_ $ _name_ $ p1-p9;
run;
data pain(type=corr);
set da2.h7q2;
run;
proc factor data=pain method=ml n=2 scree;
var p1-p9;
title 'Maximum Likelihood with 2 Factors';
run;
proc factor data=pain method=ml n=3 rotate=varimax;
var p1-p9;
title 'Maximum Likelihood with 3 factors';
run;
PROC FACTOR DATA=pain PRIORS=SMC PREPLOT PLOT
ROTATE=varimax REORDER OUTSTAT=fact_all n=3;
TITLE 'Principal factor with SMC and varimax';
RUN;
PROC FACTOR DATA=pain PRIORS=SMC PREPLOT PLOT
ROTATE=promax REORDER OUTSTAT=fact_all n=3;
TITLE 'Principal factor with SMC and PROMAX';
run;
title;

data da2.h7q4;
infile 'C:\Users\psy6b\Desktop\8320 datasets\spamdetect_train.dat' dsd;
input attr1-attr57 spam;
run;
data da2.h7q4test;
infile 'C:\Users\psy6b\Desktop\8320 datasets\spamdetect_test.dat' dsd;
input attr1-attr57 spam;
run;
PROC DISCRIM DATA=da2.h7q4 METHOD=NORMAL POOL=YES CROSSVALIDATE outstat=spam;
CLASS spam;
PRIORS PROP;
VAR attr1-attr57;
RUN;
PROC DISCRIM DATA=spam TESTDATA=da2.h7q4test TESTOUT=tout;
CLASS spam;
VAR attr1-attr57;
RUN;
PROC DISCRIM DATA=da2.h7q4 METHOD=NORMAL POOL=NO CROSSVALIDATE outstat=spam2;
CLASS spam;
PRIORS PROP;
VAR attr1-attr57;
RUN;
PROC DISCRIM DATA=spam2 TESTDATA=da2.h7q4test TESTOUT=tout2;
CLASS spam;
VAR attr1-attr57;
RUN;
proc stepdisc data=da2.h7q4 short METHOD=STEPWISE SLENTRY=.15 SLSTAY=.15;
class spam;
var attr1-attr57;
%put &_stdvar;
run;
proc discrim DATA=da2.h7q4 outstat=spam3 noprint;
CLASS spam;
var &_stdvar;
run;
PROC DISCRIM DATA=spam3 TESTDATA=da2.h7q4test TESTOUT=tout3;
CLASS spam;
var &_stdvar;
RUN;
title 'Model 1';
PROC DISCRIM DATA=da2.h7q4 METHOD=npar K=2 CROSSVALIDATE;
CLASS spam;
PRIORS PROP;
VAR attr1-attr57;
RUN;
title 'Model 2';
PROC DISCRIM DATA=da2.h7q4 METHOD=npar K=3 CROSSVALIDATE;
CLASS spam;
PRIORS PROP;
VAR attr1-attr57;
RUN;
title 'Model 3';
PROC DISCRIM DATA=da2.h7q4 METHOD=npar K=5 CROSSVALIDATE;
CLASS spam;
PRIORS PROP;
VAR attr1-attr57;
RUN;





%endoutput(class)

%write(h6re,store=class,type=listing) 

%write(h6re,store=class,type=graphic) 

