/*
 This file is auto-generated by the statrep package.
 Do not edit this file or your changes will be lost.
 Edit the LaTeX file instead.
 
 See the statrep package documentation and the file
 statrep.cfg for information on these settings.
 */
 
 
%include "./code_SR_preamble.sas" /nosource;
/* Remove all output files. */
%cleandir(., tex, tex);
%cleandir(., png, png);
%cleandir(., lst, lst);


/* Start program with a null title. */
title;

%output(class)
libname da2 'C:\Users\psy6b\Desktop\8320 datasets';
ods graphics on;
options ls=70 ps=35;

data split;
set da2.h4q4;
run;

data alzheim;
set da2.h4q5;
drop score1-score5;
run;

PROC MIXED DATA=split noitprint method=type1;
CLASS plot past min;
MODEL milk=past|min/s;
RANDOM plot plot*past/s;
RUN;

PROC MIXED DATA=split noitprint method=type1;
CLASS plot past min;
MODEL milk=past|min / ddfm=kenwardroger s;
RANDOM plot plot*past / s;
LSMEANS past / adjust=tukey;
RUN;

symbol1 interpol=join color=black line=1 repeat=47;

proc gplot data=alzheim;
where group=1;
plot score*visit=idno;
run;

proc gplot data=alzheim;
where group=2;
plot score*visit=idno;
run;

proc mixed data=alzheim method=ml noitprint;
class idno group;
model score=group*visit/ s outp=rdint;
random int/subject=idno;
run;

proc mixed data=alzheim method=ml noitprint;
class idno group;
model score=group*visit/ s outp=rdcoe;
random int visit/subject=idno type=un;
run;
proc mixed data=alzheim method=ml noitprint;
class idno group;
model score=group|visit/ s outp=rdcoe;
random int visit/subject=idno type=un;
run;

proc mixed data=alzheim noitprint;
class group visit;
model score=group*visit/ s outp=repmar;
repeated visit / subject=idno type=ar(1);
run;

proc mixed data=alzheim noitprint;
class idno group visit;
model score=group*visit/ s outp=repun;
repeated visit / subject=idno type=un;
run;

proc gplot data=rdint;
where group=1;
plot pred*visit=idno;
run;

proc gplot data=rdint;
where group=2;
plot pred*visit=idno;
run;

proc gplot data=rdcoe;
where group=1;
plot pred*visit=idno;
run;

proc gplot data=rdcoe;
where group=2;
plot pred*visit=idno;
run;

%endoutput(class)

%write(h4re,store=class,type=listing) 

%write(h4re,store=class,type=graphic) 

